name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython
    
    - name: Install Android SDK
      run: |
        wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip sdk-tools-linux-4333796.zip
        mkdir -p android-sdk
        mv tools android-sdk/
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin
        echo "y" | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-28" "build-tools;28.0.3"
    
    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$PWD/android-sdk
        export ANDROID_HOME=$PWD/android-sdk
        export PATH=$PATH:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools
        # 确保buildozer能找到完整的Android SDK
        mkdir -p ~/.buildozer/android/platform
        ln -sf $ANDROID_SDK_ROOT ~/.buildozer/android/platform/android-sdk
        buildozer android debug
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: healthapp-apk
        path: bin/*.apk